
const customerData = [
    {
      customer_id: 1,
      first_name: 'Rahul',
      last_name: 'Sharma',
      age: 32,
      country: 'India',
    },
    {
      customer_id: 2,
      first_name: 'Priya',
      last_name: 'Patel',
      age: 28,
      country: 'India',
    },
    {
      customer_id: 3,
      first_name: 'Amit',
      last_name: 'Verma',
      age: 45,
      country: 'India',
    },
    {
      customer_id: 4,
      first_name: 'Sneha',
      last_name: 'Singh',
      age: 29,
      country: 'India',
    },
    {
      customer_id: 5,
      first_name: 'Deepak',
      last_name: 'Mishra',
      age: 38,
      country: 'India',
    },
    {
      customer_id: 6,
      first_name: 'Anjali',
      last_name: 'Gupta',
      age: 24,
      country: 'India',
    },
    {
      customer_id: 7,
      first_name: 'Rajesh',
      last_name: 'Yadav',
      age: 41,
      country: 'India',
    },
    {
      customer_id: 8,
      first_name: 'Neha',
      last_name: 'Kumar',
      age: 27,
      country: 'India',
    },
    {
      customer_id: 9,
      first_name: 'Vikram',
      last_name: 'Shah',
      age: 35,
      country: 'India',
    },
    {
      customer_id: 10,
      first_name: 'Pooja',
      last_name: 'Das',
      age: 30,
      country: 'India',
    },
    {
      customer_id: 11,
      first_name: 'Arjun',
      last_name: 'Goswami',
      age: 22,
      country: 'India',
    },
    {
      customer_id: 12,
      first_name: 'Meera',
      last_name: 'Rao',
      age: 33,
      country: 'India',
    },
    {
      customer_id: 13,
      first_name: 'Sanjay',
      last_name: 'Mishra',
      age: 36,
      country: 'India',
    },
    {
      customer_id: 14,
      first_name: 'Smita',
      last_name: 'Joshi',
      age: 29,
      country: 'India',
    },
    {
      customer_id: 15,
      first_name: 'Kunal',
      last_name: 'Mehta',
      age: 34,
      country: 'India',
    },
    {
      customer_id: 16,
      first_name: 'Swati',
      last_name: 'Pandey',
      age: 31,
      country: 'India',
    },
    {
      customer_id: 17,
      first_name: 'Aryan',
      last_name: 'Sinha',
      age: 27,
      country: 'India',
    },
    {
      customer_id: 18,
      first_name: 'Anita',
      last_name: 'Rajput',
      age: 40,
      country: 'India',
    },
    {
      customer_id: 19,
      first_name: 'Ravi',
      last_name: 'Kapoor',
      age: 45,
      country: 'India',
    },
    {
      customer_id: 20,
      first_name: 'Puja',
      last_name: 'Shukla',
      age: 26,
      country: 'India',
    },
    {
      customer_id: 21,
      first_name: 'Nitin',
      last_name: 'Yadav',
      age: 29,
      country: 'India',
    },
    {
      customer_id: 22,
      first_name: 'Snehal',
      last_name: 'Chauhan',
      age: 35,
      country: 'India',
    },
    {
      customer_id: 23,
      first_name: 'Ritu',
      last_name: 'Saxena',
      age: 31,
      country: 'India',
    },
    {
      customer_id: 24,
      first_name: 'Alok',
      last_name: 'Verma',
      age: 33,
      country: 'India',
    },
    {
      customer_id: 25,
      first_name: 'Geeta',
      last_name: 'Rathore',
      age: 30,
      country: 'India',
    },
    {
      customer_id: 26,
      first_name: 'Aarav',
      last_name: 'Kumar',
      age: 28,
      country: 'India',
    },
    {
      customer_id: 27,
      first_name: 'Preeti',
      last_name: 'Bose',
      age: 37,
      country: 'India',
    },
    {
      customer_id: 28,
      first_name: 'Manoj',
      last_name: 'Chopra',
      age: 44,
      country: 'India',
    },
    {
      customer_id: 29,
      first_name: 'Suman',
      last_name: 'Gandhi',
      age: 42,
      country: 'India',
    },
    {
      customer_id: 30,
      first_name: 'Naveen',
      last_name: 'Shukla',
      age: 39,
      country: 'India',
    },
    {
      customer_id: 31,
      first_name: 'Kavita',
      last_name: 'Jain',
      age: 25,
      country: 'India',
    },
    {
      customer_id: 32,
      first_name: 'Vishal',
      last_name: 'Gupta',
      age: 28,
      country: 'India',
    },
    {
      customer_id: 33,
      first_name: 'Anita',
      last_name: 'Bhat',
      age: 43,
      country: 'India',
    },
    {
      customer_id: 34,
      first_name: 'Rohit',
      last_name: 'Mehta',
      age: 36,
      country: 'India',
    },
    {
      customer_id: 35,
      first_name: 'Priyanka',
      last_name: 'Singh',
      age: 27,
      country: 'India',
    },
    {
      customer_id: 36,
      first_name: 'Aryan',
      last_name: 'Srivastava',
      age: 30,
      country: 'India',
    },
    {
      customer_id: 37,
      first_name: 'Neelam',
      last_name: 'Sharma',
      age: 39,
      country: 'India',
    },
    {
      customer_id: 38,
      first_name: 'Kunal',
      last_name: 'Malik',
      age: 33,
      country: 'India',
    },
    {
      customer_id: 39,
      first_name: 'Shreya',
      last_name: 'Saxena',
      age: 26,
      country: 'India',
    },
    {
      customer_id: 40,
      first_name: 'Alok',
      last_name: 'Pandey',
      age: 29,
      country: 'India',
    },
    {
      customer_id: 41,
      first_name: 'Sarika',
      last_name: 'Yadav',
      age: 42,
      country: 'India',
    },
    {
      customer_id: 42,
      first_name: 'Rajesh',
      last_name: 'Rana',
      age: 31,
      country: 'India',
    },
    {
      customer_id: 43,
      first_name: 'Shubham',
      last_name: 'Mishra',
      age: 25,
      country: 'India',
    },
    {
      customer_id: 44,
      first_name: 'Anjali',
      last_name: 'Kapoor',
      age: 34,
      country: 'India',
    },
    {
      customer_id: 45,
      first_name: 'Vinod',
      last_name: 'Agarwal',
      age: 37,
      country: 'India',
    },
    {
      customer_id: 46,
      first_name: 'Rahul',
      last_name: 'Goswami',
      age: 28,
      country: 'India',
    },
    {
      customer_id: 47,
      first_name: 'Ritu',
      last_name: 'Chopra',
      age: 29,
      country: 'India',
    },
    {
      customer_id: 48,
      first_name: 'Naveen',
      last_name: 'Verma',
      age: 35,
      country: 'India',
    },
    {
      customer_id: 49,
      first_name: 'Meena',
      last_name: 'Kumar',
      age: 32,
      country: 'India',
    },
    {
      customer_id: 50,
      first_name: 'Preeti',
      last_name: 'Shukla',
      age: 27,
      country: 'India',
    },
    
  ];
  
  export default customerData;
  